const defaultPlanners = [
  {
    name: "Noida Royale Weddings",
    specialization: "Wedding Planning",
    summary:
      "Luxury wedding planners for multi-day celebrations across Noida, Greater Noida, and Delhi NCR.",
    location: "Noida",
    sector: "Sector 18",
    serviceAreas: ["Noida", "Greater Noida", "Delhi NCR", "Ghaziabad"],
    coordinates: {
      latitude: 28.5706,
      longitude: 77.3261,
    },
    supportedEventSlugs: ["weddings"],
    rating: 4.9,
    startingPrice: "INR 1.8L onwards",
    contact: {
      phone: "+91 98765 11001",
      email: "royale@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    tags: ["Luxury decor", "Destination logistics", "Bridal concierge"],
    assignedTeam: ["Ritika Sharma", "Karan Mehta", "Megha Sethi"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      startHour: "10:00",
      endHour: "20:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 240,
      blackoutDates: [],
    },
  },
  {
    name: "Delhi Shaadi Collective",
    specialization: "Wedding Planning",
    summary:
      "Delhi-based premium wedding team covering engagement, mehendi, sangeet, and reception planning.",
    location: "Delhi",
    sector: "South Delhi",
    serviceAreas: ["Delhi", "South Delhi", "Noida", "Gurgaon"],
    coordinates: {
      latitude: 28.5355,
      longitude: 77.242,
    },
    supportedEventSlugs: ["weddings"],
    rating: 4.8,
    startingPrice: "INR 2.1L onwards",
    contact: {
      phone: "+91 98765 11006",
      email: "shaadi@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=80",
    tags: ["Bridal entry", "Guest management", "Luxury wedding design"],
    assignedTeam: ["Niharika Ahuja", "Dev Malhotra", "Rohan Sethi"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      startHour: "09:00",
      endHour: "21:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 240,
      blackoutDates: [],
    },
  },
  {
    name: "Corporate Canvas Noida",
    specialization: "Corporate Events",
    summary:
      "Conference, summit, launch, and MICE specialists with strong venue and AV coordination in Noida.",
    location: "Noida",
    sector: "Sector 62",
    serviceAreas: ["Noida", "Delhi", "Greater Noida"],
    coordinates: {
      latitude: 28.6283,
      longitude: 77.3649,
    },
    supportedEventSlugs: ["corporate-mice"],
    rating: 4.7,
    startingPrice: "INR 95K onwards",
    contact: {
      phone: "+91 98765 11002",
      email: "canvas@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
    tags: ["AV production", "Registration desk", "Corporate gifting"],
    assignedTeam: ["Aman Bhatia", "Sonal Arora"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5],
      startHour: "09:00",
      endHour: "19:00",
      slotIntervalMinutes: 60,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
  {
    name: "Gurgaon MICE Masters",
    specialization: "Corporate Events",
    summary:
      "Gurgaon corporate event specialists for annual meets, product launches, trade shows, and hybrid experiences.",
    location: "Gurgaon",
    sector: "Cyber City",
    serviceAreas: ["Gurgaon", "Delhi", "Noida", "Faridabad"],
    coordinates: {
      latitude: 28.4947,
      longitude: 77.0894,
    },
    supportedEventSlugs: ["corporate-mice", "virtual-hybrid"],
    rating: 4.8,
    startingPrice: "INR 1.2L onwards",
    contact: {
      phone: "+91 98765 11007",
      email: "mice@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    tags: ["Conference ops", "Speaker logistics", "Hybrid setup"],
    assignedTeam: ["Kritika Jain", "Bhavesh Taneja"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      startHour: "08:00",
      endHour: "20:00",
      slotIntervalMinutes: 60,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
  {
    name: "Birthday Bloom Studio",
    specialization: "Birthday Parties",
    summary:
      "Theme-led birthday planning, kids entertainment, and intimate celebration design for homes and banquet halls.",
    location: "Noida",
    sector: "Sector 76",
    serviceAreas: ["Noida", "Greater Noida", "Ghaziabad"],
    coordinates: {
      latitude: 28.5678,
      longitude: 77.3824,
    },
    supportedEventSlugs: ["social-celebrations"],
    rating: 4.8,
    startingPrice: "INR 45K onwards",
    contact: {
      phone: "+91 98765 11003",
      email: "bloom@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=1200&q=80",
    tags: ["Kids entertainment", "Balloon styling", "Cake partners"],
    assignedTeam: ["Aditi Vyas", "Rohit Bansal"],
    availability: {
      acceptingBookings: true,
      workingDays: [2, 3, 4, 5, 6, 0],
      startHour: "11:00",
      endHour: "21:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
  {
    name: "Grand Mehfil Planners",
    specialization: "Social Celebrations",
    summary:
      "Anniversaries, roka, baby showers, and family functions with strong decor and hospitality execution.",
    location: "Noida",
    sector: "Sector 50",
    serviceAreas: ["Noida", "Delhi", "Ghaziabad", "Greater Noida"],
    coordinates: {
      latitude: 28.5733,
      longitude: 77.3638,
    },
    supportedEventSlugs: ["social-celebrations", "cultural-community"],
    rating: 4.6,
    startingPrice: "INR 60K onwards",
    contact: {
      phone: "+91 98765 11004",
      email: "mehfil@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80",
    tags: ["Family functions", "Decor bundles", "Host management"],
    assignedTeam: ["Vanshika Jain", "Harsh Tandon"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6, 0],
      startHour: "10:00",
      endHour: "20:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
  {
    name: "Delhi Celebration Circle",
    specialization: "Social Celebrations",
    summary:
      "Boutique celebration planners for birthdays, anniversaries, baby showers, and intimate milestone events.",
    location: "Delhi",
    sector: "West Delhi",
    serviceAreas: ["Delhi", "Noida", "Faridabad", "Ghaziabad"],
    coordinates: {
      latitude: 28.6667,
      longitude: 77.1,
    },
    supportedEventSlugs: ["social-celebrations"],
    rating: 4.7,
    startingPrice: "INR 55K onwards",
    contact: {
      phone: "+91 98765 11008",
      email: "circle@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80",
    tags: ["Home events", "Theme decor", "Live counters"],
    assignedTeam: ["Sakshi Nagpal", "Ishaan Mehra"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6, 0],
      startHour: "10:00",
      endHour: "22:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
  {
    name: "StageCraft Live Noida",
    specialization: "Concerts & Live Shows",
    summary:
      "Production-first team for college fests, public shows, and branded live experiences.",
    location: "Noida",
    sector: "Sector 137",
    serviceAreas: ["Noida", "Delhi", "Greater Noida", "Ghaziabad"],
    coordinates: {
      latitude: 28.5108,
      longitude: 77.4065,
    },
    supportedEventSlugs: ["concerts-live", "cultural-community"],
    rating: 4.8,
    startingPrice: "INR 2.4L onwards",
    contact: {
      phone: "+91 98765 11005",
      email: "stagecraft@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    tags: ["Stage design", "Artist liaison", "Crowd operations"],
    assignedTeam: ["Yash Malhotra", "Simran Gill", "Nitin Sood"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      startHour: "12:00",
      endHour: "22:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 240,
      blackoutDates: [],
    },
  },
  {
    name: "Capital Stage Syndicate",
    specialization: "Concerts & Live Shows",
    summary:
      "Delhi live event production team for concerts, college fests, and branded stage activations.",
    location: "Delhi",
    sector: "North Delhi",
    serviceAreas: ["Delhi", "Noida", "Ghaziabad", "Gurgaon"],
    coordinates: {
      latitude: 28.7269,
      longitude: 77.1425,
    },
    supportedEventSlugs: ["concerts-live", "cultural-community"],
    rating: 4.7,
    startingPrice: "INR 2.1L onwards",
    contact: {
      phone: "+91 98765 11009",
      email: "capitalstage@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
    tags: ["Sound engineer", "Talent ops", "Festival staging"],
    assignedTeam: ["Kabir Anand", "Tanya Gulati", "Varun Arora"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6, 0],
      startHour: "11:00",
      endHour: "23:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 240,
      blackoutDates: [],
    },
  },
  {
    name: "Community Connect Events",
    specialization: "Cultural & Community Events",
    summary:
      "Execution team for public festivals, school programs, and community gatherings with compliance support.",
    location: "Ghaziabad",
    sector: "Raj Nagar",
    serviceAreas: ["Ghaziabad", "Noida", "Delhi", "Greater Noida"],
    coordinates: {
      latitude: 28.6762,
      longitude: 77.4435,
    },
    supportedEventSlugs: ["cultural-community", "social-celebrations"],
    rating: 4.6,
    startingPrice: "INR 85K onwards",
    contact: {
      phone: "+91 98765 11010",
      email: "community@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
    tags: ["Permissions", "Volunteer flow", "Public event ops"],
    assignedTeam: ["Pooja Singh", "Mohit Rana"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6, 0],
      startHour: "09:00",
      endHour: "20:00",
      slotIntervalMinutes: 120,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
  {
    name: "Hybrid Horizon Studio",
    specialization: "Virtual & Hybrid Events",
    summary:
      "Hybrid, webinar, livestream, and virtual experience team with platform, AV, and moderation expertise.",
    location: "Gurgaon",
    sector: "Golf Course Road",
    serviceAreas: ["Gurgaon", "Delhi", "Noida", "Remote"],
    coordinates: {
      latitude: 28.4381,
      longitude: 77.1015,
    },
    supportedEventSlugs: ["virtual-hybrid", "corporate-mice"],
    rating: 4.9,
    startingPrice: "INR 70K onwards",
    contact: {
      phone: "+91 98765 11011",
      email: "hybrid@abhinandanevents.com",
    },
    image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    tags: ["Streaming", "Virtual stage", "Remote attendee support"],
    assignedTeam: ["Rhea Kapoor", "Aniket Sharma"],
    availability: {
      acceptingBookings: true,
      workingDays: [1, 2, 3, 4, 5, 6],
      startHour: "09:00",
      endHour: "21:00",
      slotIntervalMinutes: 60,
      defaultDurationMinutes: 180,
      blackoutDates: [],
    },
  },
];

export default defaultPlanners;
